name: mlexplain
channels:
    - conda-forge
    - defaults
    - anaconda

dependencies:
    - python=3.7
    - pip
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - statsmodels
    - lmfit
    - xgboost
    - scikit-learn
    - jupyter
    - jupyter_contrib_nbextensions
    pip:
      - lightgbm
      - interpret

